version: '3.2'
services:
  web:
    image: ${IMAGE}
    volumes:
      - /var/nfs/props/staging/assets:/app/public/assets
      - /var/nfs/props/staging/log:/app/log
    hostname: "netguru.props.staging.web"
    labels:
      - "netguru.appname=props"
      - "netguru.stage=staging"
    networks:
      - backend
    command: dumb-init bash -c "bundle exec puma -C config/puma.rb"
    environment:
      - APP_DOMAIN
      - SINGLE_DOMAIN_MODE
      - SENDGRID_USERNAME
      - SENDGRID_PASSWORD
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - DATABASE_URL
      - SECRET_KEY_BASE
      - REDISCLOUD_URL=$REDIS_URL
      - REDIS_URL
    ports:
      - "80:3000"

  sidekiq:
    image: ${IMAGE}
    volumes:
      - /var/nfs/props/staging/assets:/app/public/assets
      - /var/nfs/props/staging/log:/app/log
    hostname: "netguru.props.staging.sidekiq"
    labels:
      - "netguru.appname=props"
      - "netguru.stage=staging"
    networks:
      - backend
    environment:
      - APP_DOMAIN
      - SINGLE_DOMAIN_MODE
      - SENDGRID_USERNAME
      - SENDGRID_PASSWORD
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - DATABASE_URL
      - SECRET_KEY_BASE
      - REDISCLOUD_URL=$REDIS_URL
      - REDIS_URL
    command: dumb-init bash -c "bundle exec sidekiq --config ./config/sidekiq.staging.yml | tee -a log/staging.sidekiq.log"

  crono:
    image: ${IMAGE}
    volumes:
      - /var/nfs/props/staging/assets:/app/public/assets
      - /var/nfs/props/staging/log:/app/log
    hostname: "netguru.props.staging.crono"
    labels:
      - "netguru.appname=props"
      - "netguru.stage=staging"
    environment:
      - APP_DOMAIN
      - SINGLE_DOMAIN_MODE
      - SENDGRID_USERNAME
      - SENDGRID_PASSWORD
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - DATABASE_URL
      - SECRET_KEY_BASE
      - REDISCLOUD_URL=$REDIS_URL
      - REDIS_URL
    networks:
      - backend
    command: dumb-init bash -c "bundle exec crono -L log/staging.crono.log run | tail -f log/staging.crono.log"

networks:
  backend: 
    external:
      name: backend 
