defaults: &defaults
  newrelic_license_key: '<%= ENV["NEWRELIC_LICENSE_KEY"] %>'
  rollbar_access_token: '<%= ENV["ROLLBAR_ACCESS_TOKEN"] %>'
  secret_key_base: '<%= ENV["SECRET_KEY_BASE"] %>'
  sendgrid_user_name: '<%= ENV["SENDGRID_USER_NAME"] %>'
  sendgrid_password: '<%= ENV["SENDGRID_PASSWORD"] %>'
  slack:
    client_id: '<%= ENV["SLACK_CLIENT_ID"] %>'
    client_secret: '<%= ENV["SLACK_CLIENT_SECRET"] %>'
  skylight_token: '<%= ENV["SKYLIGHT_TOKEN"] %>'

test:
  <<: *defaults
  secret_key_base: 'f30f3887cafd21f94cbe5a06e8369c2a8cb50836382674d7f6a002984082ecd6674df59ba89b2ec86a93464c8735af48af00db39fec2f1988663c39cb81a90eb'
  
development:
  <<: *defaults
  secret_key_base: 'e1c32b26fc6e3e0bf8acceb4eda02e241664db2fd3ce8132480ca5728eee3f5a8b4f8bebe56bea5836c3de1c1ef1f4c2f003538d46b5d7dedab339c9d356128d'

staging:
  <<: *defaults

production:
  <<: *defaults
